/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mainWindow.dialogs;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;

/**
 *
 * @author Hubacek
 */
public class ImagePanel extends javax.swing.JPanel {

    /**
     * Creates new form ImagePanel
     */
    Image image;
    String location = null;

    public ImagePanel() {
        initComponents();
    }

    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        if (image != null) {
            int offsetWidth = (this.getWidth() - image.getWidth(null)) / 2;
            int offsetHeight = (this.getHeight() - image.getHeight(null)) / 2;
            g.drawImage(image, offsetWidth, offsetHeight, image.getWidth(this), image.getHeight(this), this);

            //((int)panelWidht-heightToPaint)/2
        }
    }

    public String getImageLocation() {

        return (location != null) ? this.location : null;

    }

    public void setImage(String newImageLocation) {
        if (newImageLocation != null) {
            location= newImageLocation;
            Image newImage = new ImageIcon(this.location).getImage();
            double imageWidth = newImage.getWidth(null);
            double imageHeight = newImage.getHeight(null);

            double panelWidht = this.getWidth();
            double panelHeight = this.getHeight();

            double diffHeight = imageHeight / panelHeight;
            double diffWidth = imageWidth / panelWidht;
            double ratio = (diffHeight >= diffWidth) ? diffHeight : diffWidth;

            double widthToPaint = imageWidth / ratio;
            double heightToPaint = imageHeight / ratio;

            image = getScaledImage(newImage, (int) widthToPaint, (int) heightToPaint);
            repaint();
        }
    }

    private Image getScaledImage(Image srcImg, int w, int h) {
        BufferedImage resizedImg = new BufferedImage(w, h, BufferedImage.TRANSLUCENT);
        Graphics2D g2 = resizedImg.createGraphics();
        g2.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BILINEAR);
        g2.drawImage(srcImg, 0, 0, w, h, null);
        g2.dispose();
        return resizedImg;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
